// HS Code mappings by category
export const hsCodeMappings = {
  "Electronics": [
    { code: "8471.30.00", description: "Portable automatic data processing machines, weighing not more than 10 kg, consisting of at least a central processing unit, a keyboard and a display" },
    { code: "8471.41.00", description: "Other automatic data processing machines comprising in the same housing at least a central processing unit and an input and output unit" },
    { code: "8471.50.00", description: "Processing units other than those of subheading 8471.41 or 8471.49" },
    { code: "8517.12.00", description: "Telephones for cellular networks or for other wireless networks" },
    { code: "8517.62.00", description: "Machines for the reception, conversion and transmission or regeneration of voice, images or other data" },
    { code: "8518.30.00", description: "Headphones and earphones, whether or not combined with a microphone" },
    { code: "8528.52.00", description: "Other monitors capable of directly connecting to and designed for use with an automatic data processing machine of heading 8471" },
  ],
  "Textiles & Apparel": [
    { code: "6103.10.00", description: "Men's or boys' suits, knitted or crocheted" },
    { code: "6104.13.00", description: "Women's or girls' suits of synthetic fibers, knitted or crocheted" },
    { code: "6109.10.00", description: "T-shirts, singlets and other vests, of cotton, knitted or crocheted" },
    { code: "6110.20.00", description: "Sweaters, pullovers, sweatshirts, waistcoats (vests) and similar articles, of cotton, knitted or crocheted" },
    { code: "6203.11.00", description: "Men's or boys' suits of wool or fine animal hair" },
    { code: "6204.42.00", description: "Women's or girls' dresses of cotton" },
    { code: "6212.10.00", description: "Brassieres, whether or not knitted or crocheted" },
  ],
  "Chemicals": [
    { code: "2803.00.00", description: "Carbon (carbon blacks and other forms of carbon not elsewhere specified or included)" },
    { code: "2827.35.00", description: "Nickel chloride" },
    { code: "2905.11.00", description: "Methanol (methyl alcohol)" },
    { code: "2915.21.00", description: "Acetic acid" },
    { code: "3206.49.00", description: "Other coloring matter and other preparations" },
    { code: "3208.20.00", description: "Paints and varnishes based on acrylic or vinyl polymers, in a non-aqueous medium" },
    { code: "3402.20.00", description: "Surface-active preparations, washing preparations and cleaning preparations, put up for retail sale" },
  ],
  "Machinery": [
    { code: "8413.70.00", description: "Other centrifugal pumps" },
    { code: "8414.59.00", description: "Other fans" },
    { code: "8422.30.00", description: "Machinery for filling, closing, sealing, or labeling bottles, cans, boxes, bags or other containers" },
    { code: "8428.10.00", description: "Lifts and skip hoists" },
    { code: "8443.31.00", description: "Machines which perform two or more of the functions of printing, copying or facsimile transmission" },
    { code: "8450.11.00", description: "Fully-automatic household or laundry-type washing machines, each of a dry linen capacity not exceeding 10 kg" },
    { code: "8467.21.00", description: "Drills of all kinds with self-contained electric motor" },
  ],
  "Food & Beverages": [
    { code: "0401.10.00", description: "Milk and cream, not concentrated nor containing added sugar, of a fat content, by weight, not exceeding 1%" },
    { code: "0901.21.00", description: "Coffee, roasted, not decaffeinated" },
    { code: "1101.00.00", description: "Wheat or meslin flour" },
    { code: "1806.31.00", description: "Chocolate and other food preparations containing cocoa, in blocks, slabs or bars, filled" },
    { code: "1905.31.00", description: "Sweet biscuits" },
    { code: "2009.71.00", description: "Apple juice, not fermented, Brix value <= 20" },
    { code: "2204.21.00", description: "Wine other than sparkling wine, in containers holding 2 liters or less" },
  ],
  "Pharmaceuticals": [
    { code: "3002.15.00", description: "Immunological products, put up in measured doses or in forms or packings for retail sale" },
    { code: "3003.10.00", description: "Medicaments containing penicillins or derivatives thereof" },
    { code: "3004.31.00", description: "Medicaments containing insulin, put up in measured doses or for retail sale" },
    { code: "3004.50.00", description: "Other medicaments containing vitamins or other products of heading 2936" },
    { code: "3005.10.00", description: "Adhesive dressings and other articles having an adhesive layer" },
    { code: "3006.10.00", description: "Sterile surgical catgut and similar sterile suture materials" },
    { code: "3006.60.00", description: "Chemical contraceptive preparations based on hormones" },
  ],
  "Automotive": [
    { code: "8407.32.00", description: "Spark-ignition reciprocating piston engines of a cylinder capacity exceeding 50 cc but not exceeding 250 cc" },
    { code: "8408.20.00", description: "Compression-ignition internal combustion piston engines (diesel or semi-diesel engines) of a kind used for the propulsion of vehicles of Chapter 87" },
    { code: "8413.30.00", description: "Fuel, lubricating or cooling medium pumps for internal combustion piston engines" },
    { code: "8512.20.00", description: "Other lighting or visual signaling equipment" },
    { code: "8708.10.00", description: "Bumpers and parts thereof, for motor vehicles" },
    { code: "8708.29.00", description: "Other parts and accessories of bodies for motor vehicles" },
    { code: "8708.94.00", description: "Steering wheels, steering columns and steering boxes; parts thereof" },
  ],
  "Furniture": [
    { code: "9401.30.00", description: "Swivel seats with variable height adjustment" },
    { code: "9401.71.00", description: "Other seats, with metal frames, upholstered" },
    { code: "9403.20.00", description: "Other metal furniture" },
    { code: "9403.50.00", description: "Wooden furniture of a kind used in the bedroom" },
    { code: "9403.60.00", description: "Other wooden furniture" },
    { code: "9403.90.00", description: "Parts of furniture" },
    { code: "9404.21.00", description: "Mattresses of cellular rubber or plastics, whether or not covered" },
  ],
  "Toys & Games": [
    { code: "9503.00.10", description: "Tricycles, scooters, pedal cars and similar wheeled toys; dolls' carriages" },
    { code: "9503.00.20", description: "Dolls representing only human beings" },
    { code: "9503.00.30", description: "Other toys representing animals or non-human creatures" },
    { code: "9504.20.00", description: "Articles and accessories for billiards of all kinds" },
    { code: "9504.50.00", description: "Video game consoles and machines, other than those of subheading 9504.30" },
    { code: "9505.10.00", description: "Articles for Christmas festivities" },
    { code: "9506.91.00", description: "Articles and equipment for general physical exercise, gymnastics or athletics" },
  ]
};

export default hsCodeMappings;